# Generated by Django 5.2.6 on 2025-09-29 13:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0006_category_alter_contact_image_contact_category'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Category'},
        ),
    ]
